
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACCOLADE_G = 32;
  public static final int ACCOLADE_D = 31;
  public static final int PG = 29;
  public static final int SI = 22;
  public static final int DEC_SCENARIO_FIN = 11;
  public static final int PD = 30;
  public static final int ASSOCIER = 17;
  public static final int EGALE = 38;
  public static final int DEC_SCENARII_DEBUT = 8;
  public static final int VIRGULE = 33;
  public static final int PROGRAMME_DOMUS_FIN = 3;
  public static final int DEC_INTERFACES_FIN = 7;
  public static final int DEC_SCENARIO_DEBUT = 10;
  public static final int DEC_COMMANDES_DEBUT = 12;
  public static final int CROCHET_FERMANT = 40;
  public static final int AFFECT = 39;
  public static final int TYPE_APPAREIL = 46;
  public static final int DEC_COMMANDES_FIN = 13;
  public static final int EOF = 0;
  public static final int FAIT = 28;
  public static final int ETAT = 21;
  public static final int GUILLEMET = 43;
  public static final int error = 1;
  public static final int DEC_APPAREILS_FIN = 5;
  public static final int FAIRE = 27;
  public static final int POURTOUT = 26;
  public static final int IDENT = 42;
  public static final int SINON = 25;
  public static final int ALORS = 24;
  public static final int DEC_APPAREILS_DEBUT = 4;
  public static final int EXECUTER = 18;
  public static final int AUTRE_APPAREIL = 14;
  public static final int DEUXPOINTS = 36;
  public static final int MESSAGE = 16;
  public static final int POINT = 37;
  public static final int ETAT_APPAREIL = 49;
  public static final int PROGRAMMER = 20;
  public static final int PROGRAMME_DOMUS_DEBUT = 2;
  public static final int DEC_SCENARII_FIN = 9;
  public static final int TYPE_INTERFACE = 47;
  public static final int POINTVIRGULE = 34;
  public static final int POINTEXCLAMATION = 35;
  public static final int ACTION_APPAREIL = 48;
  public static final int UNDERSCORE = 41;
  public static final int DEC_INTERFACES_DEBUT = 6;
  public static final int DEFINIR = 15;
  public static final int ENTIER = 45;
  public static final int CHAINE = 44;
  public static final int FINSI = 23;
  public static final int EXECUTER_SCENARIO = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMME_DOMUS_DEBUT",
  "PROGRAMME_DOMUS_FIN",
  "DEC_APPAREILS_DEBUT",
  "DEC_APPAREILS_FIN",
  "DEC_INTERFACES_DEBUT",
  "DEC_INTERFACES_FIN",
  "DEC_SCENARII_DEBUT",
  "DEC_SCENARII_FIN",
  "DEC_SCENARIO_DEBUT",
  "DEC_SCENARIO_FIN",
  "DEC_COMMANDES_DEBUT",
  "DEC_COMMANDES_FIN",
  "AUTRE_APPAREIL",
  "DEFINIR",
  "MESSAGE",
  "ASSOCIER",
  "EXECUTER",
  "EXECUTER_SCENARIO",
  "PROGRAMMER",
  "ETAT",
  "SI",
  "FINSI",
  "ALORS",
  "SINON",
  "POURTOUT",
  "FAIRE",
  "FAIT",
  "PG",
  "PD",
  "ACCOLADE_D",
  "ACCOLADE_G",
  "VIRGULE",
  "POINTVIRGULE",
  "POINTEXCLAMATION",
  "DEUXPOINTS",
  "POINT",
  "EGALE",
  "AFFECT",
  "CROCHET_FERMANT",
  "UNDERSCORE",
  "IDENT",
  "GUILLEMET",
  "CHAINE",
  "ENTIER",
  "TYPE_APPAREIL",
  "TYPE_INTERFACE",
  "ACTION_APPAREIL",
  "ETAT_APPAREIL"
  };
}

