/* The following code was generated by JFlex 1.7.0 */

// Specification JFlex
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>base_lex2.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\47\1\43\1\45\1\45\1\45\22\0\1\46\1\72\1\42"+
    "\5\0\1\26\1\27\2\0\1\32\1\0\1\33\1\44\12\40\1\34"+
    "\1\35\1\50\1\36\1\37\2\0\1\55\1\41\1\63\1\60\1\57"+
    "\1\70\1\54\1\41\1\66\2\41\1\64\1\56\1\67\1\53\1\51"+
    "\1\41\1\52\1\62\1\65\1\61\5\41\4\0\1\21\1\0\1\4"+
    "\1\25\1\2\1\20\1\1\1\13\1\7\1\15\1\5\1\23\1\41"+
    "\1\3\1\17\1\14\1\11\1\22\1\41\1\6\1\24\1\12\1\16"+
    "\1\10\1\41\1\71\2\41\1\30\1\46\1\31\7\0\1\45\u1fa2\0"+
    "\1\45\1\45\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\15\2\1\3\2\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\1\1\20\1\1\1\21\20\2\1\22"+
    "\12\2\1\23\1\24\1\0\1\25\5\0\1\2\1\26"+
    "\26\2\1\27\12\2\6\0\2\2\1\30\25\2\1\31"+
    "\10\2\6\0\10\2\1\32\13\2\1\26\1\2\1\33"+
    "\7\2\1\34\6\0\6\2\1\26\5\2\1\35\5\2"+
    "\1\36\5\2\6\0\5\2\1\35\10\2\1\35\1\37"+
    "\1\40\2\2\6\0\1\41\3\2\1\42\6\2\1\43"+
    "\6\0\12\2\5\0\1\44\7\2\1\45\2\0\1\46"+
    "\2\0\5\2\4\0\4\2\4\0\3\2\4\0\1\2"+
    "\1\47\7\0\1\2\12\0\1\2\12\0\1\50\5\0"+
    "\1\51\4\0\1\52\45\0\1\53\3\0\1\54\2\0"+
    "\1\55\1\56\1\0\1\57\1\60\1\0\1\61\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[409];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\73\0\166\0\261\0\354\0\u0127\0\u0162\0\u019d"+
    "\0\u01d8\0\u0213\0\u024e\0\u0289\0\u02c4\0\u02ff\0\u033a\0\u019d"+
    "\0\u0375\0\u03b0\0\73\0\73\0\73\0\73\0\73\0\73"+
    "\0\73\0\73\0\u03eb\0\73\0\u0426\0\u0461\0\73\0\u049c"+
    "\0\u04d7\0\u0512\0\73\0\u054d\0\u0588\0\u05c3\0\u05fe\0\u0639"+
    "\0\u0674\0\u06af\0\u06ea\0\u0725\0\u0760\0\u079b\0\u07d6\0\u0811"+
    "\0\u084c\0\u0887\0\u08c2\0\u019d\0\u08fd\0\u0938\0\u0973\0\u09ae"+
    "\0\u09e9\0\u0a24\0\u0a5f\0\u0a9a\0\u0ad5\0\u0b10\0\u0b4b\0\73"+
    "\0\u0461\0\73\0\u0b86\0\u0bc1\0\u0bfc\0\u0c37\0\u0c72\0\u0cad"+
    "\0\u019d\0\u0ce8\0\u0d23\0\u0d5e\0\u0d99\0\u0dd4\0\u0e0f\0\u0e4a"+
    "\0\u0e85\0\u0ec0\0\u0efb\0\u0f36\0\u0f71\0\u0fac\0\u0fe7\0\u1022"+
    "\0\u105d\0\u1098\0\u10d3\0\u110e\0\u1149\0\u1184\0\u11bf\0\u019d"+
    "\0\u11fa\0\u1235\0\u1270\0\u12ab\0\u12e6\0\u1321\0\u135c\0\u1397"+
    "\0\u13d2\0\u140d\0\u1448\0\u1483\0\u14be\0\u14f9\0\u1534\0\u156f"+
    "\0\u15aa\0\u15e5\0\u019d\0\u1620\0\u165b\0\u1696\0\u16d1\0\u170c"+
    "\0\u1747\0\u1782\0\u17bd\0\u17f8\0\u1833\0\u186e\0\u18a9\0\u18e4"+
    "\0\u191f\0\u195a\0\u1995\0\u19d0\0\u1a0b\0\u1a46\0\u1a81\0\u1abc"+
    "\0\u019d\0\u1af7\0\u1b32\0\u1b6d\0\u1ba8\0\u1be3\0\u1c1e\0\u1c59"+
    "\0\u1c94\0\u1ccf\0\u1d0a\0\u1d45\0\u1d80\0\u1dbb\0\u1df6\0\u1e31"+
    "\0\u1e6c\0\u1ea7\0\u1ee2\0\u1f1d\0\u1f58\0\u1f93\0\u1fce\0\u019d"+
    "\0\u2009\0\u2044\0\u207f\0\u20ba\0\u20f5\0\u2130\0\u216b\0\u21a6"+
    "\0\u21e1\0\u221c\0\u2257\0\u216b\0\u2292\0\u019d\0\u22cd\0\u2308"+
    "\0\u2343\0\u237e\0\u23b9\0\u23f4\0\u242f\0\u019d\0\u246a\0\u24a5"+
    "\0\u24e0\0\u251b\0\u2556\0\u2591\0\u25cc\0\u2607\0\u2642\0\u267d"+
    "\0\u26b8\0\u26f3\0\u272e\0\u2769\0\u27a4\0\u27df\0\u281a\0\u2855"+
    "\0\u2890\0\u28cb\0\u2906\0\u2941\0\u297c\0\u29b7\0\u019d\0\u29f2"+
    "\0\u2a2d\0\u2a68\0\u2aa3\0\u2ade\0\u2b19\0\u2b54\0\u2b8f\0\u2bca"+
    "\0\u2c05\0\u2c40\0\u2c7b\0\u2cb6\0\u2cf1\0\u2d2c\0\u2d67\0\u2da2"+
    "\0\u2ddd\0\u2e18\0\u2e53\0\u2e8e\0\u2ec9\0\u2f04\0\u2f3f\0\u2f7a"+
    "\0\u019d\0\u019d\0\u019d\0\u2fb5\0\u2ff0\0\u302b\0\u3066\0\u30a1"+
    "\0\u30dc\0\u3117\0\u3152\0\u318d\0\u31c8\0\u3203\0\u323e\0\u019d"+
    "\0\u3279\0\u32b4\0\u32ef\0\u332a\0\u3365\0\u33a0\0\u019d\0\u33db"+
    "\0\u3416\0\u3451\0\u348c\0\u34c7\0\u3502\0\u353d\0\u3578\0\u35b3"+
    "\0\u35ee\0\u3629\0\u3664\0\u369f\0\u36da\0\u3715\0\u3750\0\u378b"+
    "\0\u37c6\0\u3801\0\u383c\0\u3877\0\73\0\u38b2\0\u38ed\0\u3928"+
    "\0\u3963\0\u399e\0\u39d9\0\u3a14\0\u019d\0\u3a4f\0\u3a8a\0\73"+
    "\0\u3ac5\0\u3b00\0\u3b3b\0\u3b76\0\u3bb1\0\u3bec\0\u3c27\0\u3c62"+
    "\0\u3c9d\0\u3cd8\0\u3d13\0\u3d4e\0\u3d89\0\u3dc4\0\u3dff\0\u3e3a"+
    "\0\u3e75\0\u3eb0\0\u3eeb\0\u3f26\0\u3f61\0\u3f9c\0\u3fd7\0\u4012"+
    "\0\u404d\0\u4088\0\u40c3\0\u019d\0\u40fe\0\u4139\0\u4174\0\u41af"+
    "\0\u41ea\0\u4225\0\u4260\0\u429b\0\u42d6\0\u4311\0\u434c\0\u4387"+
    "\0\u43c2\0\u43fd\0\u4438\0\u4473\0\u44ae\0\u44e9\0\u4524\0\u455f"+
    "\0\u459a\0\u45d5\0\u4610\0\u464b\0\u4686\0\u46c1\0\u46fc\0\u4737"+
    "\0\u4772\0\u019d\0\u47ad\0\u47e8\0\u4823\0\u485e\0\u4899\0\73"+
    "\0\u48d4\0\u490f\0\u494a\0\u4985\0\73\0\u49c0\0\u49fb\0\u4a36"+
    "\0\u4a71\0\u4aac\0\u4ae7\0\u4b22\0\u4b5d\0\u4b98\0\u4bd3\0\u4c0e"+
    "\0\u4c49\0\u4c84\0\u4cbf\0\u4cfa\0\u4d35\0\u4d70\0\u4dab\0\u4de6"+
    "\0\u4e21\0\u4e5c\0\u4e97\0\u4ed2\0\u4f0d\0\u4f48\0\u4f83\0\u4fbe"+
    "\0\u4ff9\0\u5034\0\u506f\0\u50aa\0\u50e5\0\u5120\0\u515b\0\u5196"+
    "\0\u51d1\0\u520c\0\73\0\u5247\0\u5282\0\u52bd\0\73\0\u52f8"+
    "\0\u5333\0\73\0\73\0\u536e\0\73\0\73\0\u53a9\0\73"+
    "\0\73";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[409];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\10\1\11"+
    "\1\12\1\13\1\14\1\10\1\15\1\10\1\16\1\17"+
    "\1\20\1\21\1\10\1\22\1\10\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\10\1\36\1\37\1\40\1\0\1\37\1\41\1\42"+
    "\21\10\1\43\74\0\1\10\1\44\7\10\1\45\13\10"+
    "\12\0\2\10\7\0\20\10\1\46\2\0\3\10\1\47"+
    "\10\10\1\50\10\10\12\0\2\10\7\0\21\10\2\0"+
    "\3\10\1\51\21\10\12\0\2\10\7\0\21\10\2\0"+
    "\2\10\1\52\12\10\1\53\5\10\1\54\1\10\12\0"+
    "\2\10\7\0\21\10\2\0\13\10\1\55\11\10\12\0"+
    "\2\10\7\0\21\10\2\0\25\10\12\0\2\10\7\0"+
    "\21\10\2\0\4\10\1\56\3\10\1\57\14\10\12\0"+
    "\2\10\7\0\21\10\2\0\5\10\1\60\7\10\1\61"+
    "\7\10\12\0\2\10\7\0\21\10\2\0\1\62\2\10"+
    "\1\63\3\10\1\64\15\10\12\0\2\10\7\0\21\10"+
    "\2\0\1\65\2\10\1\66\17\10\1\67\1\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\70\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\71\7\10\1\72\14\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\73\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\5\10\1\74\2\10\1\75"+
    "\14\10\12\0\2\10\7\0\21\10\2\0\1\76\3\10"+
    "\1\77\20\10\12\0\2\10\7\0\21\10\37\0\1\100"+
    "\74\0\1\35\32\0\42\101\1\102\1\0\27\101\44\0"+
    "\1\103\71\0\1\37\73\0\1\104\4\0\1\105\6\0"+
    "\1\106\1\0\1\107\11\0\2\10\1\110\5\10\1\111"+
    "\14\10\12\0\2\10\7\0\21\10\2\0\1\112\2\10"+
    "\1\113\21\10\12\0\2\10\7\0\21\10\2\0\1\114"+
    "\24\10\12\0\2\10\7\0\21\10\2\0\12\10\1\115"+
    "\12\10\12\0\2\10\7\0\21\10\2\0\3\10\1\116"+
    "\21\10\12\0\2\10\7\0\21\10\2\0\7\10\1\117"+
    "\15\10\12\0\2\10\7\0\21\10\2\0\2\10\1\120"+
    "\1\121\4\10\1\122\14\10\12\0\2\10\7\0\21\10"+
    "\2\0\11\10\1\123\13\10\12\0\2\10\7\0\21\10"+
    "\2\0\23\10\1\124\1\10\12\0\2\10\7\0\21\10"+
    "\2\0\11\10\1\125\13\10\12\0\2\10\7\0\21\10"+
    "\2\0\17\10\1\126\5\10\12\0\2\10\7\0\21\10"+
    "\2\0\2\10\1\127\22\10\12\0\2\10\7\0\21\10"+
    "\2\0\17\10\1\130\5\10\12\0\2\10\7\0\21\10"+
    "\2\0\7\10\1\131\15\10\12\0\2\10\7\0\21\10"+
    "\2\0\2\10\1\132\22\10\12\0\2\10\7\0\21\10"+
    "\2\0\16\10\1\133\5\10\1\134\12\0\2\10\7\0"+
    "\21\10\2\0\5\10\1\135\5\10\1\136\11\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\137\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\140\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\12\10\1\141\12\10\12\0"+
    "\2\10\7\0\21\10\2\0\23\10\1\142\1\10\12\0"+
    "\2\10\7\0\21\10\2\0\24\10\1\143\12\0\2\10"+
    "\7\0\21\10\2\0\12\10\1\144\3\10\1\145\6\10"+
    "\12\0\2\10\7\0\21\10\2\0\10\10\1\146\14\10"+
    "\12\0\2\10\7\0\21\10\2\0\5\10\1\147\7\10"+
    "\1\150\7\10\12\0\2\10\7\0\21\10\2\0\1\10"+
    "\1\151\23\10\12\0\2\10\7\0\21\10\2\0\13\10"+
    "\1\152\11\10\12\0\2\10\7\0\21\10\1\0\43\103"+
    "\1\37\1\103\1\0\25\103\51\0\1\153\6\0\1\154"+
    "\1\0\1\155\62\0\1\156\77\0\1\157\76\0\1\160"+
    "\10\0\3\10\1\161\21\10\12\0\2\10\7\0\21\10"+
    "\2\0\4\10\1\162\20\10\12\0\2\10\7\0\21\10"+
    "\2\0\11\10\1\163\13\10\12\0\2\10\7\0\21\10"+
    "\2\0\1\10\1\164\23\10\12\0\2\10\7\0\21\10"+
    "\2\0\1\165\24\10\12\0\2\10\7\0\21\10\2\0"+
    "\15\10\1\166\7\10\12\0\2\10\7\0\21\10\2\0"+
    "\1\167\24\10\12\0\2\10\7\0\21\10\2\0\15\10"+
    "\1\170\7\10\12\0\2\10\7\0\21\10\2\0\5\10"+
    "\1\171\17\10\12\0\2\10\7\0\21\10\2\0\5\10"+
    "\1\172\17\10\12\0\2\10\7\0\21\10\2\0\5\10"+
    "\1\173\17\10\12\0\2\10\7\0\21\10\2\0\10\10"+
    "\1\174\14\10\12\0\2\10\7\0\21\10\2\0\1\175"+
    "\24\10\12\0\2\10\7\0\21\10\2\0\1\176\24\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\177\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\200\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\201\4\10\1\202\17\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\203\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\204\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\2\10\1\205\22\10\12\0"+
    "\2\10\7\0\21\10\2\0\16\10\1\206\6\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\207\24\10\12\0\2\10"+
    "\7\0\21\10\2\0\5\10\1\210\3\10\1\211\13\10"+
    "\12\0\2\10\7\0\21\10\2\0\4\10\1\64\20\10"+
    "\12\0\2\10\7\0\21\10\2\0\23\10\1\212\1\10"+
    "\12\0\2\10\7\0\21\10\2\0\4\10\1\213\20\10"+
    "\12\0\2\10\7\0\21\10\2\0\4\10\1\214\20\10"+
    "\12\0\2\10\7\0\21\10\2\0\4\10\1\111\20\10"+
    "\12\0\2\10\7\0\21\10\2\0\6\10\1\215\16\10"+
    "\12\0\2\10\7\0\21\10\2\0\11\10\1\216\13\10"+
    "\12\0\2\10\7\0\21\10\2\0\5\10\1\217\17\10"+
    "\12\0\2\10\7\0\21\10\2\0\14\10\1\220\10\10"+
    "\12\0\2\10\7\0\21\10\2\0\10\10\1\221\14\10"+
    "\12\0\2\10\7\0\21\10\53\0\1\222\77\0\1\223"+
    "\76\0\1\224\62\0\1\225\102\0\1\226\66\0\1\227"+
    "\14\0\4\10\1\230\20\10\12\0\2\10\7\0\21\10"+
    "\2\0\13\10\1\231\11\10\12\0\2\10\7\0\21\10"+
    "\2\0\15\10\1\232\7\10\12\0\2\10\7\0\21\10"+
    "\2\0\11\10\1\233\13\10\12\0\2\10\7\0\21\10"+
    "\2\0\12\10\1\234\12\10\12\0\2\10\7\0\21\10"+
    "\2\0\20\10\1\235\4\10\12\0\2\10\7\0\21\10"+
    "\2\0\16\10\1\236\6\10\12\0\2\10\7\0\21\10"+
    "\2\0\16\10\1\237\6\10\12\0\2\10\7\0\21\10"+
    "\2\0\23\10\1\240\1\10\12\0\2\10\7\0\21\10"+
    "\2\0\1\241\24\10\12\0\2\10\7\0\21\10\2\0"+
    "\1\10\1\242\23\10\12\0\2\10\7\0\21\10\2\0"+
    "\5\10\1\243\17\10\12\0\2\10\7\0\21\10\2\0"+
    "\10\10\1\244\14\10\12\0\2\10\7\0\21\10\2\0"+
    "\11\10\1\64\13\10\12\0\2\10\7\0\21\10\2\0"+
    "\13\10\1\245\11\10\12\0\2\10\7\0\21\10\2\0"+
    "\5\10\1\246\17\10\12\0\2\10\7\0\21\10\2\0"+
    "\4\10\1\247\20\10\12\0\2\10\7\0\21\10\2\0"+
    "\1\10\1\250\17\10\1\251\3\10\12\0\2\10\7\0"+
    "\21\10\2\0\23\10\1\252\1\10\12\0\2\10\7\0"+
    "\21\10\2\0\1\253\24\10\12\0\2\10\7\0\21\10"+
    "\2\0\1\254\24\10\12\0\2\10\7\0\21\10\2\0"+
    "\11\10\1\255\13\10\12\0\2\10\7\0\21\10\2\0"+
    "\1\256\24\10\12\0\2\10\7\0\21\10\2\0\3\10"+
    "\1\257\21\10\12\0\2\10\7\0\21\10\2\0\2\10"+
    "\1\260\22\10\12\0\2\10\7\0\21\10\2\0\13\10"+
    "\1\261\11\10\12\0\2\10\7\0\21\10\2\0\5\10"+
    "\1\262\17\10\12\0\2\10\7\0\21\10\2\0\3\10"+
    "\1\263\21\10\12\0\2\10\7\0\21\10\2\0\11\10"+
    "\1\264\13\10\12\0\2\10\7\0\21\10\2\0\1\265"+
    "\24\10\12\0\2\10\7\0\21\10\2\0\13\10\1\266"+
    "\11\10\12\0\2\10\7\0\21\10\54\0\1\267\102\0"+
    "\1\270\66\0\1\271\67\0\1\272\102\0\1\273\75\0"+
    "\1\274\4\0\5\10\1\275\17\10\12\0\2\10\7\0"+
    "\21\10\2\0\11\10\1\111\5\10\1\276\5\10\12\0"+
    "\2\10\7\0\21\10\2\0\11\10\1\277\13\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\300\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\12\10\1\275\12\10\12\0"+
    "\2\10\7\0\21\10\2\0\2\10\1\301\4\10\1\302"+
    "\15\10\12\0\2\10\7\0\21\10\2\0\1\303\24\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\64\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\20\10\1\304\4\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\305\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\5\10\1\306\17\10\12\0"+
    "\2\10\7\0\21\10\2\0\20\10\1\307\4\10\12\0"+
    "\2\10\7\0\21\10\2\0\3\10\1\310\21\10\12\0"+
    "\2\10\7\0\21\10\2\0\11\10\1\111\13\10\12\0"+
    "\2\10\7\0\21\10\2\0\5\10\1\311\17\10\12\0"+
    "\2\10\7\0\21\10\2\0\10\10\1\312\14\10\12\0"+
    "\2\10\7\0\21\10\2\0\14\10\1\313\10\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\314\24\10\12\0\2\10"+
    "\7\0\21\10\2\0\11\10\1\315\13\10\12\0\2\10"+
    "\7\0\21\10\2\0\5\10\1\237\17\10\12\0\2\10"+
    "\7\0\21\10\2\0\6\10\1\316\16\10\12\0\2\10"+
    "\7\0\21\10\2\0\1\317\24\10\12\0\2\10\7\0"+
    "\21\10\2\0\4\10\1\320\20\10\12\0\2\10\7\0"+
    "\21\10\2\0\3\10\1\321\21\10\12\0\2\10\7\0"+
    "\21\10\2\0\4\10\1\322\20\10\12\0\2\10\7\0"+
    "\21\10\2\0\10\10\1\323\14\10\12\0\2\10\7\0"+
    "\21\10\2\0\20\10\1\324\4\10\12\0\2\10\7\0"+
    "\21\10\55\0\1\325\102\0\1\326\75\0\1\327\55\0"+
    "\1\330\75\0\1\331\72\0\1\332\16\0\3\10\1\333"+
    "\21\10\12\0\2\10\7\0\21\10\2\0\5\10\1\334"+
    "\17\10\12\0\2\10\7\0\21\10\2\0\1\335\24\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\255\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\4\10\1\336\20\10\12\0"+
    "\2\10\7\0\21\10\2\0\3\10\1\337\21\10\12\0"+
    "\2\10\7\0\21\10\2\0\5\10\1\340\17\10\12\0"+
    "\2\10\7\0\21\10\2\0\3\10\1\341\21\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\342\24\10\12\0\2\10"+
    "\7\0\21\10\2\0\15\10\1\343\7\10\12\0\2\10"+
    "\7\0\21\10\2\0\21\10\1\344\3\10\12\0\2\10"+
    "\7\0\21\10\2\0\11\10\1\345\13\10\12\0\2\10"+
    "\7\0\21\10\2\0\20\10\1\346\4\10\12\0\2\10"+
    "\7\0\21\10\2\0\16\10\1\347\6\10\12\0\2\10"+
    "\7\0\21\10\2\0\10\10\1\350\14\10\12\0\2\10"+
    "\7\0\21\10\2\0\5\10\1\351\17\10\12\0\2\10"+
    "\7\0\21\10\2\0\11\10\1\260\13\10\12\0\2\10"+
    "\7\0\21\10\2\0\1\352\24\10\12\0\2\10\7\0"+
    "\21\10\2\0\5\10\1\353\17\10\12\0\2\10\7\0"+
    "\21\10\2\0\16\10\1\354\6\10\12\0\2\10\7\0"+
    "\21\10\2\0\2\10\1\64\22\10\12\0\2\10\7\0"+
    "\21\10\2\0\15\10\1\355\7\10\12\0\2\10\7\0"+
    "\21\10\2\0\2\10\1\301\22\10\12\0\2\10\7\0"+
    "\21\10\53\0\1\356\75\0\1\357\72\0\1\360\72\0"+
    "\1\361\67\0\1\362\72\0\1\363\21\0\6\10\1\237"+
    "\16\10\12\0\2\10\7\0\21\10\2\0\1\351\24\10"+
    "\12\0\2\10\7\0\21\10\2\0\5\10\1\364\17\10"+
    "\12\0\2\10\7\0\21\10\2\0\13\10\1\333\11\10"+
    "\12\0\2\10\7\0\21\10\2\0\4\10\1\365\20\10"+
    "\12\0\2\10\7\0\21\10\2\0\20\10\1\366\4\10"+
    "\12\0\2\10\7\0\21\10\2\0\21\10\1\367\3\10"+
    "\12\0\2\10\7\0\21\10\2\0\5\10\1\370\17\10"+
    "\12\0\2\10\7\0\21\10\2\0\21\10\1\371\3\10"+
    "\12\0\2\10\7\0\21\10\2\0\5\10\1\372\17\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\373\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\21\10\1\374\3\10\12\0"+
    "\2\10\7\0\21\10\2\0\16\10\1\375\6\10\12\0"+
    "\2\10\7\0\21\10\2\0\13\10\1\260\11\10\12\0"+
    "\2\10\7\0\21\10\2\0\16\10\1\376\6\10\12\0"+
    "\2\10\7\0\21\10\2\0\11\10\1\377\13\10\12\0"+
    "\2\10\7\0\21\10\56\0\1\u0100\67\0\1\u0101\72\0"+
    "\1\u0102\76\0\1\u0103\71\0\1\u0104\103\0\1\u0105\5\0"+
    "\20\10\1\u0106\4\10\12\0\2\10\7\0\21\10\2\0"+
    "\23\10\1\u0107\1\10\12\0\2\10\7\0\21\10\2\0"+
    "\1\u0108\20\10\1\374\3\10\12\0\2\10\7\0\21\10"+
    "\2\0\21\10\1\u0109\3\10\12\0\2\10\7\0\21\10"+
    "\2\0\11\10\1\u010a\13\10\12\0\2\10\7\0\21\10"+
    "\2\0\10\10\1\u010b\14\10\12\0\2\10\7\0\21\10"+
    "\2\0\15\10\1\u010c\7\10\12\0\2\10\7\0\21\10"+
    "\2\0\3\10\1\u010d\21\10\12\0\2\10\7\0\21\10"+
    "\2\0\3\10\1\u010e\21\10\12\0\2\10\7\0\21\10"+
    "\2\0\1\u010f\24\10\12\0\2\10\7\0\21\10\57\0"+
    "\1\u0110\71\0\1\u0111\103\0\1\u0112\62\0\1\u0113\101\0"+
    "\1\u0114\60\0\1\u0115\20\0\23\10\1\u0116\1\10\12\0"+
    "\2\10\7\0\21\10\2\0\23\10\1\u0117\1\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\10\1\u0118\23\10\12\0"+
    "\2\10\7\0\21\10\2\0\3\10\1\u0119\21\10\12\0"+
    "\2\10\7\0\21\10\2\0\1\u011a\24\10\12\0\2\10"+
    "\7\0\21\10\2\0\22\10\1\64\2\10\12\0\2\10"+
    "\7\0\21\10\2\0\5\10\1\64\17\10\12\0\2\10"+
    "\7\0\21\10\2\0\5\10\1\u011b\17\10\12\0\2\10"+
    "\7\0\21\10\2\0\13\10\1\u011c\11\10\12\0\2\10"+
    "\7\0\21\10\2\0\5\10\1\u011d\17\10\12\0\2\10"+
    "\7\0\21\10\57\0\1\u011e\101\0\1\u011f\60\0\1\u0120"+
    "\76\0\1\u0121\101\0\1\u0122\5\0\1\10\1\u0123\23\10"+
    "\12\0\2\10\7\0\21\10\2\0\1\u0124\24\10\12\0"+
    "\2\10\7\0\21\10\2\0\10\10\1\351\14\10\12\0"+
    "\2\10\7\0\21\10\2\0\5\10\1\u0125\17\10\12\0"+
    "\2\10\7\0\21\10\2\0\15\10\1\u0126\7\10\12\0"+
    "\2\10\7\0\21\10\2\0\11\10\1\u0127\13\10\12\0"+
    "\2\10\7\0\21\10\2\0\17\10\1\260\5\10\12\0"+
    "\2\10\7\0\21\10\60\0\1\u0128\101\0\1\u0129\25\0"+
    "\1\u012a\124\0\1\u012b\20\0\1\u012c\24\10\12\0\2\10"+
    "\7\0\21\10\2\0\2\10\1\u012d\22\10\12\0\2\10"+
    "\7\0\21\10\2\0\1\u012e\24\10\12\0\2\10\7\0"+
    "\21\10\2\0\5\10\1\317\17\10\12\0\2\10\7\0"+
    "\21\10\2\0\4\10\1\u012f\20\10\12\0\2\10\7\0"+
    "\21\10\22\0\1\u0130\124\0\1\u0131\77\0\1\u0132\101\0"+
    "\1\u0133\4\0\13\10\1\u0134\11\10\12\0\2\10\7\0"+
    "\21\10\2\0\2\10\1\237\22\10\12\0\2\10\7\0"+
    "\21\10\2\0\4\10\1\u0135\20\10\12\0\2\10\7\0"+
    "\21\10\2\0\1\u0136\24\10\12\0\2\10\7\0\21\10"+
    "\61\0\1\u0137\101\0\1\u0138\56\0\1\u0139\40\0\1\u013a"+
    "\52\0\3\10\1\u013b\21\10\12\0\2\10\7\0\21\10"+
    "\2\0\2\10\1\u013c\22\10\12\0\2\10\7\0\21\10"+
    "\2\0\2\10\1\351\22\10\12\0\2\10\7\0\21\10"+
    "\54\0\1\u013d\40\0\1\u013e\127\0\1\u013f\71\0\1\u0140"+
    "\4\0\1\u0141\1\u0142\2\0\1\u0143\5\0\5\10\1\u0144"+
    "\17\10\12\0\2\10\7\0\21\10\57\0\1\u0145\71\0"+
    "\1\u0146\4\0\1\u0147\1\u0148\2\0\1\u0149\65\0\1\u014a"+
    "\62\0\1\u014b\104\0\1\u014c\62\0\1\u014d\106\0\1\u014e"+
    "\4\0\4\10\1\u014f\20\10\12\0\2\10\7\0\21\10"+
    "\62\0\1\u0150\62\0\1\u0151\104\0\1\u0152\62\0\1\u0153"+
    "\106\0\1\u0154\65\0\1\u0155\61\0\1\u0156\100\0\1\u0157"+
    "\71\0\1\u0158\101\0\1\u0159\6\0\10\10\1\u015a\14\10"+
    "\12\0\2\10\7\0\21\10\63\0\1\u015b\61\0\1\u015c"+
    "\100\0\1\u015d\71\0\1\u015e\101\0\1\u015f\44\0\1\u0160"+
    "\110\0\1\u0161\104\0\1\u0162\61\0\1\u0163\73\0\1\u0164"+
    "\52\0\1\u0165\110\0\1\u0166\104\0\1\u0167\61\0\1\u0168"+
    "\73\0\1\u0169\65\0\1\u016a\75\0\1\u016b\72\0\1\u016c"+
    "\67\0\1\u016d\72\0\1\u016e\75\0\1\u016f\72\0\1\u0170"+
    "\67\0\1\u0171\77\0\1\u0172\65\0\1\u0173\107\0\1\u0174"+
    "\73\0\1\u0175\61\0\1\u0176\65\0\1\u0177\107\0\1\u0178"+
    "\73\0\1\u0179\70\0\1\u017a\72\0\1\u017b\64\0\1\u017c"+
    "\67\0\1\u017d\103\0\1\u017e\72\0\1\u017f\64\0\1\u0180"+
    "\67\0\1\u0181\101\0\1\u0182\74\0\1\u0183\63\0\1\u0184"+
    "\76\0\1\u0185\73\0\1\u0186\74\0\1\u0187\63\0\1\u0188"+
    "\76\0\1\u0189\71\0\1\u018a\47\0\1\u018b\115\0\1\u018c"+
    "\67\0\1\u018d\75\0\1\u018e\47\0\1\u018f\115\0\1\u0190"+
    "\67\0\1\u0191\52\0\1\u0192\72\0\1\u0193\115\0\1\u0194"+
    "\47\0\1\u0195\72\0\1\u0196\115\0\1\u0197\47\0\1\u0198"+
    "\72\0\1\u0199\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[21476];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\20\1\10\11\1\1\1\11\2\1\1\11"+
    "\3\1\1\11\34\1\1\11\1\0\1\11\5\0\43\1"+
    "\6\0\41\1\6\0\37\1\6\0\30\1\6\0\23\1"+
    "\6\0\14\1\6\0\12\1\5\0\1\11\10\1\2\0"+
    "\1\11\2\0\5\1\4\0\4\1\4\0\3\1\4\0"+
    "\2\1\7\0\1\1\12\0\1\1\12\0\1\1\5\0"+
    "\1\11\4\0\1\11\45\0\1\11\3\0\1\11\2\0"+
    "\2\11\1\0\2\11\1\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[409];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	public int getYyLine(){
		return yyline+1;
	}
	public int getYyColumn(){
		return yycolumn+1;
	}
	public String getYyText(){
		return yytext();
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println(" Erreur ligne "+(yyline+1)+" colonne "+(yycolumn+1)+" : "+ yytext()+" => caractère inconnu ! ");
            } 
            // fall through
          case 51: break;
          case 2: 
            { return new Symbol(sym.IDENT , new String(yytext()));
            } 
            // fall through
          case 52: break;
          case 3: 
            { return new Symbol(sym.UNDERSCORE);
            } 
            // fall through
          case 53: break;
          case 4: 
            { return new Symbol(sym.PG);
            } 
            // fall through
          case 54: break;
          case 5: 
            { return new Symbol(sym.PD);
            } 
            // fall through
          case 55: break;
          case 6: 
            { return new Symbol(sym.ACCOLADE_G);
            } 
            // fall through
          case 56: break;
          case 7: 
            { return new Symbol(sym.ACCOLADE_D);
            } 
            // fall through
          case 57: break;
          case 8: 
            { return new Symbol(sym.VIRGULE);
            } 
            // fall through
          case 58: break;
          case 9: 
            { return new Symbol(sym.POINT);
            } 
            // fall through
          case 59: break;
          case 10: 
            { return new Symbol(sym.DEUXPOINTS);
            } 
            // fall through
          case 60: break;
          case 11: 
            { return new Symbol(sym.POINTVIRGULE);
            } 
            // fall through
          case 61: break;
          case 12: 
            { return new Symbol(sym.AFFECT);
            } 
            // fall through
          case 62: break;
          case 13: 
            { return new Symbol(sym.CROCHET_FERMANT);
            } 
            // fall through
          case 63: break;
          case 14: 
            { return new Symbol(sym.ENTIER, new Integer(yytext()));
            } 
            // fall through
          case 64: break;
          case 15: 
            { return new Symbol(sym.GUILLEMET, new String( yytext()));
            } 
            // fall through
          case 65: break;
          case 16: 
            { 
            } 
            // fall through
          case 66: break;
          case 17: 
            { return new Symbol(sym.POINTEXCLAMATION , yytext());
            } 
            // fall through
          case 67: break;
          case 18: 
            { return new Symbol(sym.TYPE_APPAREIL, new String( yytext()));
            } 
            // fall through
          case 68: break;
          case 19: 
            { return new Symbol(sym.SI , yytext());
            } 
            // fall through
          case 69: break;
          case 20: 
            { return new Symbol(sym.EGALE);
            } 
            // fall through
          case 70: break;
          case 21: 
            { return new Symbol(sym.CHAINE, new String(yytext()));
            } 
            // fall through
          case 71: break;
          case 22: 
            { return new Symbol(sym.ETAT_APPAREIL, new String( yytext()));
            } 
            // fall through
          case 72: break;
          case 23: 
            { return new Symbol(sym.FINSI , yytext());
            } 
            // fall through
          case 73: break;
          case 24: 
            { return new Symbol(sym.ETAT , yytext());
            } 
            // fall through
          case 74: break;
          case 25: 
            { return new Symbol(sym.FAIT , yytext());
            } 
            // fall through
          case 75: break;
          case 26: 
            { return new Symbol(sym.ALORS , yytext());
            } 
            // fall through
          case 76: break;
          case 27: 
            { return new Symbol(sym.FAIRE , yytext());
            } 
            // fall through
          case 77: break;
          case 28: 
            { return new Symbol(sym.SINON , yytext());
            } 
            // fall through
          case 78: break;
          case 29: 
            { return new Symbol(sym.ACTION_APPAREIL, new String( yytext()));
            } 
            // fall through
          case 79: break;
          case 30: 
            { return new Symbol(sym.TYPE_INTERFACE, new String( yytext()));
            } 
            // fall through
          case 80: break;
          case 31: 
            { return new Symbol(sym.MESSAGE , yytext());
            } 
            // fall through
          case 81: break;
          case 32: 
            { return new Symbol(sym.DEFINIR , yytext());
            } 
            // fall through
          case 82: break;
          case 33: 
            { return new Symbol(sym.EXECUTER , yytext());
            } 
            // fall through
          case 83: break;
          case 34: 
            { return new Symbol(sym.ASSOCIER , yytext());
            } 
            // fall through
          case 84: break;
          case 35: 
            { return new Symbol(sym.POURTOUT , yytext());
            } 
            // fall through
          case 85: break;
          case 36: 
            { return new Symbol(sym.DEC_SCENARIO_DEBUT , yytext());
            } 
            // fall through
          case 86: break;
          case 37: 
            { return new Symbol(sym.PROGRAMMER , yytext());
            } 
            // fall through
          case 87: break;
          case 38: 
            { return new Symbol(sym.DEC_SCENARIO_FIN , yytext());
            } 
            // fall through
          case 88: break;
          case 39: 
            { return new Symbol(sym.AUTRE_APPAREIL , yytext());
            } 
            // fall through
          case 89: break;
          case 40: 
            { return new Symbol(sym.EXECUTER_SCENARIO , yytext());
            } 
            // fall through
          case 90: break;
          case 41: 
            { return new Symbol(sym.PROGRAMME_DOMUS_DEBUT , yytext());
            } 
            // fall through
          case 91: break;
          case 42: 
            { return new Symbol(sym.PROGRAMME_DOMUS_FIN , yytext());
            } 
            // fall through
          case 92: break;
          case 43: 
            { return new Symbol(sym.DEC_SCENARII_DEBUT , yytext());
            } 
            // fall through
          case 93: break;
          case 44: 
            { return new Symbol(sym.DEC_SCENARII_FIN , yytext());
            } 
            // fall through
          case 94: break;
          case 45: 
            { return new Symbol(sym.DEC_APPAREILS_DEBUT , yytext());
            } 
            // fall through
          case 95: break;
          case 46: 
            { return new Symbol(sym.DEC_COMMANDES_DEBUT , yytext());
            } 
            // fall through
          case 96: break;
          case 47: 
            { return new Symbol(sym.DEC_APPAREILS_FIN , yytext());
            } 
            // fall through
          case 97: break;
          case 48: 
            { return new Symbol(sym.DEC_COMMANDES_FIN , yytext());
            } 
            // fall through
          case 98: break;
          case 49: 
            { return new Symbol(sym.DEC_INTERFACES_DEBUT , yytext());
            } 
            // fall through
          case 99: break;
          case 50: 
            { return new Symbol(sym.DEC_INTERFACES_FIN , yytext());
            } 
            // fall through
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
